
ARGS:
 tab: 'webcam'
 GPUS: 0 
 multi_person: True
 kernel_sizes: [5]
 use_coordmaps: True
 fine_tune: True
 eval: False

 baseline: 'hrnetv5'
 input_size: 512
 centermap_size: 64
 model_precision: 'fp16'
 val_batch_size: 2
 gmodel_path: '../trained_models/pw3d_81.8_58.6.pkl'

 # default: run on demo/images save at demo/images_results
 # for video /path/to/project/CenterHMR/demo/videos/Messi_1
 demo_image_folder: None
 save_mesh: False
 save_centermap: False
 save_dict_results: False

 webcam: True
 cam_id: 0
 webcam_mesh_color: 'ghostwhite'  #'LightCyan'
 run_on_remote_server: False
 server_ip: 'localhost'
 server_port: 10086